### ISSUE TITLE
Ctrl+click/F3 is not working for external types (eg Java standard API)

### ISSUE THREAD

**Issue by mickaelistria** [mickaelistria/eclipse.jdt.ls.client#8]
Create a dummy
```java
class A {
  String s;
}
```
edit it in Generic editor and Ctrl+click on `String`.
EXPECTED: jump to source code for String
GOT: nothing.

**Comment by mickaelistria** [comment]
This requires a way to open an editor for URIs of the form `jdt://contents/java.base/java.util/Collection.class?\u003dblah/%5C/usr%5C/lib%5C/jvm%5C/java-19-openjdk%5C/lib%5C/jrt-fs.jar%60java.base\u003d/javadoc_location\u003d/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/19%5C/docs%5C/api%5C/\u003d/\u003d/module\u003d/true\u003d/%3Cjava.util(Collection.class`, and then to select the right location in the editor.
Most likely LSP4E will need to be extended to turn such URI to proper IEditorInput.

**Comment by mickaelistria** [comment]
This topic seems to require changes in multiple places:
* a `jdt:/` URL protocol handler that would be capable of getting the contents from this URL. That shouldn't be too hard and JDT-LS probably has most of it available (cc @rgrunber?)
* Then building a kind of EditorInput that can take content from random URLs.
* Then enabling a document provider that can use such EditorInput to build a document with the content of the stream pointed by the URL
* Then make the text editor use such document provider for such editor input

**Comment by mickaelistria** [comment]
another approach is to implement an IFileSystem for `jdt:` scheme. This is probably what would work best (if this can work)

**Comment by rgrunber** [comment]
Yup, there's a bit of non-protocol stuff going on here in order to handle classfiles.

See https://github.com/eclipse/eclipse.jdt.ls/issues/2322#issuecomment-1313953316 where I try my best to explain what a client needs to do in order to handle this.

Basically, the client's "Java" extension needs to declare it owns/supports the `jdt` file scheme. Then whenever the language server returns a location of the form `jdt://....`, you immediately call back the language server with `java/classFileContents` and the URI you just received. The language server will respond with the raw data needed and you can use that to render the file in an editor.

**Comment by mickaelistria** [comment]
As mentioned in https://github.com/eclipse/eclipse.jdt.ls/issues/2465 , I think having JDT-LS sending `jar:file:/...` URIs whenever available would be much simpler.

**Comment by mickaelistria** [comment]
I believe we can consider it fixed from an Eclipse IDE POV. Further related issues will be opened later.
